name: Moodle Plugin Release

on:
  release:
    types: [ published ]

jobs:
  call-moodle-release-workflow:
    uses: bycs-lp/moodle-workflows/.github/workflows/moodle-release.yml@main
    with:
      plugin-name: 'quizaccess_ai'
    secrets: inherit
